### ISSUE TITLE
Would be cool to have the Elite Prefix in the death cause.

### ISSUE THREAD

**Issue by ghost** [NotTsunami/ShowDeathCause#1]
Just like Player was killed by Overloading Enemy for example. Found no issues great mod

**Comment by ghost** [comment]
If you use 
{ RoR2.Util.GetBestBodyName(damageReport.attacker) }
instead of
{ damageReport.attackerBody.GetDisplayName() }
it will display the elite prefix and umbra prefix.

**Comment by NotTsunami** [comment]
> If you use { RoR2.Util.GetBestBodyName(damageReport.attacker) } instead of { damageReport.attackerBody.GetDisplayName() } it will display the elite prefix and umbra prefix.

Thanks for this suggestion! `RoR2.Util.GetBestBodyName()` requires a GameObject, so the full call is actually `Util.GetBestBodyName(_damageReport.attackerBody.gameObject)`, but it does function better than `damageReport.attackerBody.GetDisplayName()`, and lets me remove that null check.

I have some other changes I'm gonna push out too in the next couple days. I'll close this once I push the update!
![image](https://user-images.githubusercontent.com/4589807/137022542-13708a4c-e18b-44df-82da-8d2695c0da72.png)
