### ISSUE TITLE
NRE spam after death

### ISSUE THREAD

**Issue by breadguyyy** [NotTsunami/ShowDeathCause#2]
getting this spammed after dying to a jellyfish in SP:

> [Warning: Unity Log] Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
> [Error  : Unity Log] NullReferenceException
> Stack trace:
> ShowDeathCause.ShowDeathCause.<Awake>b__1_1 (On.RoR2.UI.GameEndReportPanelController+orig_SetPlayerInfo orig, RoR2.UI.GameEndReportPanelController self, RoR2.RunRepo
> rt+PlayerInfo playerInfo) (at <5cb9efe3512f489c8caf389ac7fa970c>:IL_009C)
> DMD<>?1971306752.Hook<RoR2.UI.GameEndReportPanelController::SetPlayerInfo>?-336621824 (RoR2.UI.GameEndReportPanelController , RoR2.RunReport+PlayerInfo ) (at <bfb690e6ac6146c29f91076ccd66b3e7>:IL_0014)
> RoR2.UI.GameEndReportPanelController.SetDisplayData (RoR2.UI.GameEndReportPanelController+DisplayData newDisplayData) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_027D)
> RoR2.GameOverController.GenerateReportScreen (RoR2.UI.HUD hud) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0081)
> RoR2.GameOverController.UpdateReportScreens () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0031)
> RoR2.GameOverController.Update () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0000)

full log here:
[LogOutput.log](https://github.com/NotTsunami/ShowDeathCause/files/7430201/LogOutput.log)

**Comment by NotTsunami** [comment]
> getting this spammed after dying to a jellyfish in SP:
> 
> > [Warning: Unity Log] Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
> > [Error  : Unity Log] NullReferenceException
> > Stack trace:
> > ShowDeathCause.ShowDeathCause.b__1_1 (On.RoR2.UI.GameEndReportPanelController+orig_SetPlayerInfo orig, RoR2.UI.GameEndReportPanelController self, RoR2.RunRepo
> > rt+PlayerInfo playerInfo) (at <5cb9efe3512f489c8caf389ac7fa970c>:IL_009C)
> > DMD<>?1971306752.Hook<RoR2.UI.GameEndReportPanelController::SetPlayerInfo>?-336621824 (RoR2.UI.GameEndReportPanelController , RoR2.RunReport+PlayerInfo ) (at :IL_0014)
> > RoR2.UI.GameEndReportPanelController.SetDisplayData (RoR2.UI.GameEndReportPanelController+DisplayData newDisplayData) (at :IL_027D)
> > RoR2.GameOverController.GenerateReportScreen (RoR2.UI.HUD hud) (at :IL_0081)
> > RoR2.GameOverController.UpdateReportScreens () (at :IL_0031)
> > RoR2.GameOverController.Update () (at :IL_0000)
> 
> full log here: [LogOutput.log](https://github.com/NotTsunami/ShowDeathCause/files/7430201/LogOutput.log)

Interesting, thank you for the report. Is this happening on every death or only against a Jellyfish? I will look into this further over the weekend.

**Comment by NotTsunami** [comment]
This should be fixed by the latest update now. Thanks for the report, and please open an issue or ping me on the Risk of Rain 2 modding discord if you encounter any more issues!
